
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class f3page extends javax.swing.JFrame {

    /**
     * Creates new form f3page
     */
    public f3page() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        s2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        s3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        s4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        s5 = new javax.swing.JTextField();
        s6 = new javax.swing.JTextField();
        s7 = new javax.swing.JTextField();
        s8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        usn = new javax.swing.JTextField();
        bid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        usn1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("UPDATE STUDENT EXAM DETAILS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 10, 375, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("SGPA1");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 190, 53, 22);

        s1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(s1);
        s1.setBounds(360, 180, 65, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("SGPA2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 270, 53, 22);

        s2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        jPanel1.add(s2);
        s2.setBounds(360, 260, 65, 28);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("SGPA3");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 330, 53, 22);

        s3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(s3);
        s3.setBounds(360, 330, 65, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("SGPA4");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 400, 53, 22);

        s4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(s4);
        s4.setBounds(360, 400, 65, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("SGPA5");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(500, 190, 53, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("SGPA6");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(500, 260, 53, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("SGPA7");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(500, 330, 53, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("SGPA8");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(510, 410, 53, 22);

        s5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        jPanel1.add(s5);
        s5.setBounds(670, 190, 74, 28);

        s6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(s6);
        s6.setBounds(670, 260, 74, 28);

        s7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(s7);
        s7.setBounds(670, 330, 74, 28);

        s8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        s8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s8ActionPerformed(evt);
            }
        });
        jPanel1.add(s8);
        s8.setBounds(670, 400, 74, 28);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("CGPA");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(340, 470, 44, 22);

        c.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel1.add(c);
        c.setBounds(430, 470, 64, 28);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 510, 99, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(510, 510, 82, 33);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("USN");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(230, 110, 34, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("BRANCH ID");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(500, 110, 93, 22);

        usn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(usn);
        usn.setBounds(360, 110, 120, 23);

        bid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(bid);
        bid.setBounds(670, 110, 74, 28);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Enter USN");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(290, 50, 81, 22);

        usn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usn1KeyPressed(evt);
            }
        });
        jPanel1.add(usn1);
        usn1.setBounds(480, 50, 150, 28);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i9.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 0, 1010, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s2ActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s5ActionPerformed

    private void s8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s8ActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
             Class.forName("com.mysql.jdbc.Driver");
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/student", "root", "dolly");
             
             String sql;
             String n=null;
             
             sql="update EXAMS set SGPA1=?,SGPA2=?,SGPA3=?,SGPA4=?,SGPA5=?,SGPA6=?,SGPA7=?,SGPA8=?,CGPA=? where USN=?";
             PreparedStatement pst=conn.prepareStatement(sql);
            
             int a2=s1.getDocument().getLength();
             int a3=s2.getDocument().getLength();
             int a8=s3.getDocument().getLength();
             int a5=s4.getDocument().getLength();
             int a6=s5.getDocument().getLength();
             int a7=s6.getDocument().getLength();
             int a9=s7.getDocument().getLength();
              int a10=s8.getDocument().getLength();
              int a11=c.getDocument().getLength();
              
             if((a2==0)||(a5==0)||(a6==0)||(a9==0)||(a3==0)||(a8==0)||(a7==0)||(a10==0)||(a11==0))
             {
                   
                            JOptionPane.showMessageDialog(null, "Please Enter All The Details");
                     
             }
          
             else{             
                 pst.setString(1, s1.getText());
                 pst.setString(2, s2.getText());
                 pst.setString(3, s3.getText());
                 pst.setString(4, s4.getText());
                 pst.setString(5, s5.getText());
                 pst.setString(6, s6.getText());
                 pst.setString(7, s7.getText());
                 pst.setString(8,s8.getText());
                 pst.setString(9, c.getText());
                 pst.setString(10,usn.getText());
                  
                                 int k= pst.executeUpdate();
                                 if(k==1)
                                 {
                                 JOptionPane.showMessageDialog(null, "successfully Updated "+  usn.getText()+ " In Exams");
                                 usn.setText(null);
                                 
                                 s1.setText(null);
                                 s2.setText(null);
                                 s3.setText(null);
                                 s4.setText(null);
                                 s5.setText(null);
                                 s6.setText(null);
                                s7.setText(null);
                                s8.setText(null);
                                 c.setText(null);
                                bid.setText(null);
                                 }
                                 else
                                 {
                                     JOptionPane.showMessageDialog(null, "Not updated");
                                 usn.setText(null);
                                 
                                s1.setText(null);
                                 s2.setText(null);
                                 s3.setText(null);
                                 s4.setText(null);
                                 s5.setText(null);
                                 s6.setText(null);
                                s7.setText(null);
                                s8.setText(null);
                                 c.setText(null);
                                bid.setText(null);
                                 }
                                 
                             
                                 
                              
                                     
                                 
             }
        }
            
        
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        f1page f1=new f1page();
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void usn1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usn1KeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try{
             Class.forName("com.mysql.jdbc.Driver");
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/student", "root", "dolly");
            String sql="select * from EXAMS where USN=?";
            PreparedStatement pst=conn.prepareStatement(sql);
            int a1=usn1.getDocument().getLength();
            if(a1==0)
            {
                JOptionPane.showMessageDialog(null,"Please enter usn");
                
            }
            else
            {
                pst.setString(1,usn1.getText());
                ResultSet rs=pst.executeQuery();
                if(!rs.next())
                {
                    JOptionPane.showMessageDialog(null, "usn does not exist");
                    usn1.setText(null);
                    
                }
                else
                {
                    bid.setText(rs.getString("branch_id"));                   
                    usn.setText(rs.getString("usn"));
                    s1.setText(rs.getString("sgpa1"));
                    s2.setText(rs.getString("sgpa2"));
                    s3.setText(rs.getString("sgpa3"));
                    s4.setText(rs.getString("sgpa4"));
                    s5.setText(rs.getString("sgpa5"));
                    s6.setText(rs.getString("sgpa6"));
                     s7.setText(rs.getString("sgpa7"));
                    s8.setText(rs.getString("sgpa8"));
                    c.setText(rs.getString("cgpa"));
                    
                    conn.close();;
                }   
            }
}
        catch(Exception e)
            
        {
            JOptionPane.showMessageDialog(null, e);
        }
         
        }
    }//GEN-LAST:event_usn1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f3page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f3page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f3page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f3page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f3page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bid;
    private javax.swing.JTextField c;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JTextField s5;
    private javax.swing.JTextField s6;
    private javax.swing.JTextField s7;
    private javax.swing.JTextField s8;
    private javax.swing.JTextField usn;
    private javax.swing.JTextField usn1;
    // End of variables declaration//GEN-END:variables
}
