
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Tpage extends javax.swing.JFrame {

    /**
     * Creates new form Tpage
     */
    public Tpage() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel5 = new javax.swing.JPanel();
        jTxt29 = new javax.swing.JLabel();
        jTxt30 = new javax.swing.JLabel();
        jTxt31 = new javax.swing.JLabel();
        jTxt32 = new javax.swing.JLabel();
        jTxt33 = new javax.swing.JLabel();
        jTxt34 = new javax.swing.JLabel();
        jTxt35 = new javax.swing.JLabel();
        jTxt37 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        cid = new javax.swing.JTextField();
        jTxt36 = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        sal = new javax.swing.JTextField();
        qua = new javax.swing.JTextField();
        pno = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel5.setLayout(null);

        jTxt29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxt29.setText("FACULTY ID");
        jPanel5.add(jTxt29);
        jTxt29.setBounds(240, 110, 180, 20);

        jTxt30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxt30.setText("FACULTY NAME");
        jPanel5.add(jTxt30);
        jTxt30.setBounds(240, 150, 180, 22);

        jTxt31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxt31.setText("COURSE ID");
        jPanel5.add(jTxt31);
        jTxt31.setBounds(240, 200, 180, 22);

        jTxt32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxt32.setText("BRANCH ID");
        jPanel5.add(jTxt32);
        jTxt32.setBounds(240, 250, 180, 22);

        jTxt33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxt33.setText("FACULTY SALARY");
        jPanel5.add(jTxt33);
        jTxt33.setBounds(240, 300, 180, 22);

        jTxt34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxt34.setText("QUALIFICATIONS");
        jPanel5.add(jTxt34);
        jTxt34.setBounds(240, 350, 180, 22);

        jTxt35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxt35.setText("PHONE NUMBER");
        jPanel5.add(jTxt35);
        jTxt35.setBounds(240, 400, 180, 22);

        jTxt37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxt37.setText("ADDRESS");
        jPanel5.add(jTxt37);
        jTxt37.setBounds(240, 440, 180, 22);

        id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel5.add(id);
        id.setBounds(400, 100, 317, 28);

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        jPanel5.add(name);
        name.setBounds(400, 150, 317, 28);

        cid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidActionPerformed(evt);
            }
        });
        jPanel5.add(cid);
        cid.setBounds(400, 200, 317, 28);

        jTxt36.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTxt36.setText("INSERT NEW FACULTY");
        jPanel5.add(jTxt36);
        jTxt36.setBounds(161, 22, 382, 44);

        bid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidActionPerformed(evt);
            }
        });
        jPanel5.add(bid);
        bid.setBounds(400, 250, 317, 28);

        sal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel5.add(sal);
        sal.setBounds(400, 300, 317, 28);

        qua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaActionPerformed(evt);
            }
        });
        jPanel5.add(qua);
        qua.setBounds(400, 350, 317, 28);

        pno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pnoKeyReleased(evt);
            }
        });
        jPanel5.add(pno);
        pno.setBounds(400, 390, 317, 28);

        add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addKeyPressed(evt);
            }
        });
        jPanel5.add(add);
        add.setBounds(400, 440, 317, 28);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(490, 530, 93, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(640, 530, 77, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i9.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(0, 0, 980, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidActionPerformed

    private void bidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidActionPerformed

    private void quaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quaActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here
             SqlDao obj = new SqlDao();
        SqlDao obj2 = new SqlDao();
       
        Spage s=new Spage();
        
        int f1 = id.getDocument().getLength();
        int f2 = name.getDocument().getLength();
        int f3=cid.getDocument().getLength();
        int f4 = bid.getDocument().getLength();
        int f5 = sal.getDocument().getLength();
        int f6 = qua.getDocument().getLength();
         int f8 = pno.getDocument().getLength();
         if(f8!=10)
         {
               JOptionPane.showMessageDialog(null, " Phone no has only 10 digits, please enter properly");
                pno.setText(null);
           pno.requestFocusInWindow();
         }
        int f7 = add.getDocument().getLength();
        if(f1==0||f2==0||f4==0||f5==0||f3==0||f4==0||f5==0||f6==0||f7==0||f8==0 ){
            JOptionPane.showMessageDialog(null, "Please enter the details properly");
        }else{
            try {
                
               int n;
                n = obj.insertFaculty(id.getText(),name.getText(), cid.getText(), bid.getText(), sal.getText(), qua.getText(), pno.getText(), add.getText());
                if(n==0){
                   JOptionPane.showMessageDialog(null, "Data not inserted");
                }
            
                else{
                    JOptionPane.showMessageDialog(null, "Data inserted successfully");
                }
                
            
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null,ex);
            }
        }
   
        
        

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fpage f=new fpage();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addKeyPressed
 if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
                  SqlDao obj = new SqlDao();
        SqlDao obj2 = new SqlDao();
        
        Spage s=new Spage();
        
        int f1 = id.getDocument().getLength();
        int f2 = name.getDocument().getLength();
        int f3=cid.getDocument().getLength();
        int f4 = bid.getDocument().getLength();
        int f5 = sal.getDocument().getLength();
        int f6 = qua.getDocument().getLength();
         int f8 = pno.getDocument().getLength();
        int f7 = add.getDocument().getLength();
        if(f1==0||f2==0||f4==0||f5==0||f3==0||f4==0||f5==0||f6==0||f7==0||f8==0 ){
            JOptionPane.showMessageDialog(null, "Please enter the details properly");
        }else{
            try {
                
               int n;
                n = obj.insertFaculty(id.getText(),name.getText(), cid.getText(), bid.getText(), sal.getText(), qua.getText(), pno.getText(), add.getText());
                if(n==0){
                   JOptionPane.showMessageDialog(null, "Data not inserted");
                }
            
                else{
                    JOptionPane.showMessageDialog(null, "Data inserted successfully");
                }
                
            
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null,ex);
            }
        }
                    // TODO add your handling code here:
    }//GEN-LAST:event_addKeyPressed
    }
    private void pnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnoKeyReleased
        // TODO add your handling code here:
         signup c=new signup();
        int f =pno.getDocument().getLength();
         boolean a= c.checknumber(pno.getText());
            
            if(a){
                 JOptionPane.showMessageDialog(null, " Characters are not allowed ,please enter numbers");
                 pno.setText(null);
           pno.requestFocusInWindow();
            }
           
    }//GEN-LAST:event_pnoKeyReleased

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        // TODO add your handling code here:
             signup c=new signup();
       boolean a= c.checkstring(name.getText());
       if(a)
       {
           JOptionPane.showMessageDialog(null,"Please enter characters , numbers are not allowed");
           name.setText(null);
           name.requestFocusInWindow();
       }
    }//GEN-LAST:event_nameKeyReleased
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField bid;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JLabel jTxt29;
    private javax.swing.JLabel jTxt30;
    private javax.swing.JLabel jTxt31;
    private javax.swing.JLabel jTxt32;
    private javax.swing.JLabel jTxt33;
    private javax.swing.JLabel jTxt34;
    private javax.swing.JLabel jTxt35;
    private javax.swing.JLabel jTxt36;
    private javax.swing.JLabel jTxt37;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pno;
    private javax.swing.JTextField qua;
    private javax.swing.JTextField sal;
    // End of variables declaration//GEN-END:variables
}
